# Generated by Django 4.2.1 on 2023-05-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='about',
            field=models.CharField(max_length=1500),
        ),
    ]
