# Generated by Django 4.2.1 on 2023-05-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_details_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='filims',
            name='image',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
